version: '3'

services:

  php8.1:
    build: ./php
    volumes:
      - ./converter:/var/www/html/converter
    ports:
      - 9000:9000

  converter:
    image: nginx
    volumes:
      - ./converter:/var/www/html/converter
      - ./components/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    links:
      - php8.1
    depends_on:
      - php8.1


  db:
    image: mysql
    command: mysqld --skip-external-locking --collation-server="utf8mb4_unicode_ci" --character-set-server="utf8mb4" --init_connect="SET collation_connection = utf8mb4_unicode_ci" --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: converter
      MYSQL_DATABASE: converter